apiVersion: v1
kind: Service
metadata:
  name: cliptown-api
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: cliptown-api
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
